<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE ngsql:schema [
<!ELEMENT ngsql:schema (schema*,dataNode*,dataSource*)>
<!ATTLIST ngsql:schema xmlns:ngsql CDATA #FIXED "http://ngsql.12306ng.com/">

<!ELEMENT schema (table*)>
<!ATTLIST schema name NMTOKEN #REQUIRED>
<!ATTLIST schema dataNode CDATA #IMPLIED>
<!ATTLIST schema group CDATA #IMPLIED>
<!ATTLIST schema keepSqlSchema NMTOKEN #IMPLIED>
<!ELEMENT table (property*)>
<!ATTLIST table name CDATA #REQUIRED>
<!ATTLIST table dataNode CDATA #REQUIRED>
<!ATTLIST table rule NMTOKEN #IMPLIED>
<!ATTLIST table ruleRequired NMTOKEN #IMPLIED>

<!ELEMENT dataNode (property+)>
<!ATTLIST dataNode name NMTOKEN #REQUIRED>

<!ELEMENT dataSource (property+)>
<!ATTLIST dataSource name NMTOKEN #REQUIRED>
<!ATTLIST dataSource type NMTOKEN #REQUIRED>

<!ELEMENT property ( #PCDATA | bean | dataSourceRef | location )*>
<!ATTLIST property name NMTOKEN #REQUIRED>

<!ELEMENT bean (property*)>
<!ATTLIST bean name NMTOKEN #IMPLIED>
<!ATTLIST bean class NMTOKEN #REQUIRED>

<!ELEMENT dataSourceRef (#PCDATA)>
<!ELEMENT location (#PCDATA)>
]>
<ngsql:schema xmlns:ngsql="http://ngsql.12306ng.com/">

  <!-- schema定义 -->
  <schema name="dbtest" dataNode="dnTest1">
    <table name="tb2" dataNode="dnTest2,dnTest3" rule="rule1" />
  </schema>

  <!-- 数据节点定义，数据节点由数据源和其他一些参数组织而成。-->
  <dataNode name="dnTest1">
    <property name="dataSource">
      <dataSourceRef>dsTest[0]</dataSourceRef>
    </property>
  </dataNode>
  <dataNode name="dnTest2">
    <property name="dataSource">
      <dataSourceRef>dsTest[1]</dataSourceRef>
    </property>
  </dataNode>
  <dataNode name="dnTest3">
    <property name="dataSource">
      <dataSourceRef>dsTest[2]</dataSourceRef>
    </property>
  </dataNode>

  <!-- 数据源定义，数据源是一个具体的后端数据连接的表示。-->
  <dataSource name="dsTest" type="mysql">
    <property name="location">
      <location>192.168.0.1:3306/dbtest1</location>
      <location>192.168.0.1:3306/dbtest2</location>
      <location>192.168.0.1:3306/dbtest3</location>
    </property>
    <property name="user">test</property>
    <property name="password"></property>
    <property name="sqlMode">STRICT_TRANS_TABLES</property>
  </dataSource>

</ngsql:schema>
